"""
Code generator — produces a CrewAI boilerplate script from an AgentRoster dict.
"""

import json
import re


def generate_crewai_script(agentifyx_data) -> str:
    """
    Parse the AgentRoster output (dict or JSON string) and generate a CrewAI
    boilerplate Python script.
    """
    try:
        # Accept both dict and JSON string
        if isinstance(agentifyx_data, str):
            clean_str = agentifyx_data.replace("```json", "").replace("```", "").strip()
            data = json.loads(clean_str)
        elif isinstance(agentifyx_data, dict):
            data = agentifyx_data
        else:
            data = {}

        # Support both old ("proposed_agents") and new ("agents") schema
        agents = data.get("agents", data.get("proposed_agents", []))

        script = '"""Auto-generated by AgentifyX — CrewAI Agentic Architecture"""\n\n'
        script += "from crewai import Agent, Crew, Process, Task\n\n"

        agent_names: list[str] = []
        for i, agent in enumerate(agents):
            # New schema uses "agent_name" / "role"; old uses "role" only
            role = agent.get("role", agent.get("agent_name", f"Agent_{i}"))
            var_name = re.sub(r"[^a-z0-9_]", "", role.lower().replace(" ", "_").replace("&", "and"))
            if not var_name:
                var_name = f"agent_{i}"
            agent_names.append(var_name)

            goal = agent.get("goal", "")
            tools = agent.get("tools_required", agent.get("tools_needed", []))
            hitl = agent.get("hitl_required", False)

            script += f"# --- {role} ---\n"
            script += f"{var_name} = Agent(\n"
            script += f'    role="{role}",\n'
            script += f'    goal="{goal}",\n'
            script += f'    backstory="You are a senior {role}. You execute your goals flawlessly.",\n'
            script += f"    verbose=True,\n"
            script += f"    allow_delegation=False,\n"

            if hitl:
                script += f"    # HITL required: {agent.get('hitl_checkpoints', [])}\n"
            if tools:
                script += f"    # Tools needed: {tools}\n"

            script += ")\n\n"

        # Tasks placeholder
        script += "# --- Define Tasks ---\n"
        for i, name in enumerate(agent_names):
            script += f"task_{i} = Task(\n"
            script += f'    description="TODO: Define task for {name}",\n'
            script += f'    expected_output="TODO: Define expected output",\n'
            script += f"    agent={name},\n"
            script += ")\n\n"

        # Crew assembly
        script += "# --- Assemble the Crew ---\n"
        script += "agentifyx_crew = Crew(\n"
        script += f"    agents=[{', '.join(agent_names)}],\n"
        script += f"    tasks=[{', '.join(f'task_{i}' for i in range(len(agent_names)))}],\n"

        framework = data.get("recommended_framework", "CrewAI")
        script += f"    process=Process.sequential,  # Recommended: {framework}\n"
        script += "    verbose=True,\n"
        script += ")\n\n"

        # Summary comment
        summary = data.get("transformation_summary", "")
        if summary:
            script += f'# Transformation Summary:\n# {summary[:200]}\n\n'

        readiness = data.get("composite_readiness", "N/A")
        script += f"# Composite Readiness Score: {readiness}\n\n"

        script += 'if __name__ == "__main__":\n'
        script += '    print("Starting Agentic Workflow...")\n'
        script += "    result = agentifyx_crew.kickoff()\n"
        script += "    print(result)\n"

        return script

    except Exception as e:
        raw = str(agentifyx_data)[:500] if agentifyx_data else "None"
        return f"# Error generating script: {e}\n# Raw input was:\n# {raw}\n"